name: JKafka CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Limpar e montar o projeto
      run: mvn clean install -Dmaven.test.skip
    - name: Testes para Producer
      run: mvn test -f ./producer/pom.xml
    - name: Testes para Consumer-Email
      run: mvn test -f ./consumer-email/pom.xml
